"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ANALYSIS_RESULT_STORAGE_KEY, RECOMMENDATION_STORAGE_KEY } from "@/lib/recommend/types";

const steps = ["국가와 시간대", "피부 타입", "민감도", "고민", "피부 톤", "언더톤", "알레르기", "피하고 싶은 성분", "현재 사용 제품", "선호", "케어 동의"];
const fields = ["country", "skinType", "sensitivity", "concerns", "toneDepth", "undertone", "allergyIngredients", "avoidedIngredients", "currentProducts", "preferences", "consentCareTracking"] as const;
type Form = Record<(typeof fields)[number], string> & { timezone: string };
const initial = (): Form => ({country:"KR",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone || "Asia/Seoul",skinType:"",sensitivity:"",concerns:"",toneDepth:"",undertone:"",allergyIngredients:"",avoidedIngredients:"",currentProducts:"",preferences:"",consentCareTracking:""});

export default function OnboardingPage() {
 const router=useRouter(); const [step,setStep]=useState(0); const [form,setForm]=useState<Form>(initial); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{try{const rec=JSON.parse(localStorage.getItem(RECOMMENDATION_STORAGE_KEY)||"null");const analysis=JSON.parse(localStorage.getItem(ANALYSIS_RESULT_STORAGE_KEY)||"null");setForm(old=>({...old,skinType:rec?.skinType??analysis?.skin_type??"",concerns:Array.isArray(rec?.skinConcerns)?rec.skinConcerns.join(", "):old.concerns,allergyIngredients:Array.isArray(rec?.allergyIngredients)?rec.allergyIngredients.join(", "):old.allergyIngredients,avoidedIngredients:Array.isArray(rec?.avoidedIngredients)?rec.avoidedIngredients.join(", "):old.avoidedIngredients,currentProducts:Array.isArray(rec?.currentProducts)?rec.currentProducts.map((p:{productName?:string})=>p.productName).filter(Boolean).join(", "):old.currentProducts}));}catch{}},[]);
 const field=fields[step]; const split=(value:string)=>value.split(",").map(v=>v.trim()).filter(Boolean);
 async function finish(){if(form.consentCareTracking!=="yes"){setError("케어 기록 저장 동의가 필요합니다.");return;}setBusy(true);try{const res=await fetch("/api/care/analyses",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({timezone:form.timezone,country:form.country,skinType:form.skinType||null,sensitivity:form.sensitivity||null,concerns:split(form.concerns),toneDepth:form.toneDepth||null,undertone:form.undertone||null,allergyIngredients:split(form.allergyIngredients),avoidedIngredients:split(form.avoidedIngredients),currentProducts:split(form.currentProducts),analysisSnapshot:{},recommendationSnapshot:{preferences:form.preferences},rankedProductIds:[],dataConfidence:null,consentCareTracking:true})});if(res.status===401){router.push("/login?next=%2Fonboarding");return;}if(!res.ok)throw new Error();router.push("/my?onboarded=1");router.refresh();}catch{setError("저장에 실패했습니다. 잠시 후 다시 시도해 주세요.");}finally{setBusy(false);}}
 const labels:Record<string,string>={country:"국가",skinType:"피부 타입",sensitivity:"민감도",concerns:"고민 (쉼표로 여러 개 입력)",toneDepth:"피부 톤 깊이",undertone:"언더톤",allergyIngredients:"알레르기 성분",avoidedIngredients:"피하고 싶은 성분",currentProducts:"현재 사용 제품",preferences:"향·제형·예산 선호"};
 return <main className="min-h-screen bg-[#FAF7F5] px-4 py-10"><div className="mx-auto max-w-xl rounded-2xl bg-white p-6"><p className="text-sm text-[#C2185B]">{step+1} / {steps.length}</p><div className="mt-2 h-2 rounded bg-pink-100"><div className="h-2 rounded bg-[#C2185B]" style={{width:`${((step+1)/steps.length)*100}%`}} /></div><h1 className="mt-6 text-2xl font-bold">{steps[step]}</h1>{field==="consentCareTracking"?<label className="mt-6 flex gap-2 text-sm"><input type="checkbox" checked={form.consentCareTracking==="yes"} onChange={e=>setForm({...form,consentCareTracking:e.target.checked?"yes":""})}/>내 케어 기록을 계정에 저장하는 데 동의합니다.</label>:<label className="mt-6 block text-sm">{labels[field]}<input value={form[field]} onChange={e=>setForm({...form,[field]:e.target.value})} className="mt-2 w-full rounded-lg border border-[#E8DFD8] px-3 py-2" /></label>}{error&&<p className="mt-3 text-sm text-rose-700">{error}</p>}<div className="mt-8 flex justify-between"><button disabled={!step} onClick={()=>setStep(step-1)} className="rounded-lg px-4 py-2 disabled:opacity-40">이전</button>{step===steps.length-1?<button disabled={busy} onClick={()=>void finish()} className="rounded-lg bg-[#C2185B] px-4 py-2 text-white">{busy?"저장 중…":"완료"}</button>:<button onClick={()=>setStep(step+1)} className="rounded-lg bg-[#C2185B] px-4 py-2 text-white">다음</button>}</div></div></main>;
}
