/**
 * Fixture entities for P3-T03 automated refresh ops (non-public).
 */

import type { RefreshEntityRecord, SourceSnapshot } from "./types";

function snap(partial: Partial<SourceSnapshot>): SourceSnapshot {
  return {
    name: partial.name ?? null,
    officialUrl: partial.officialUrl ?? null,
    priceAmount: partial.priceAmount ?? null,
    currency: partial.currency ?? null,
    inStock: partial.inStock ?? null,
    ingredientsFingerprint: partial.ingredientsFingerprint ?? null,
    imageUrl: partial.imageUrl ?? null,
    operatingStatus: partial.operatingStatus ?? null,
    specialtyCount: partial.specialtyCount ?? null,
    evidenceFingerprint: partial.evidenceFingerprint ?? null,
  };
}

/** Fixed "now" companion: 2026-07-24T12:00:00.000Z */
export function createAutomatedRefreshFixtures(): RefreshEntityRecord[] {
  return [
    {
      entityId: "prod-current-001",
      entityKind: "product",
      displayName: "Fixture Serum Current",
      collectedAt: "2026-07-20T00:00:00.000Z",
      verifiedAt: "2026-07-20T00:00:00.000Z",
      refreshDueAt: "2026-08-20T00:00:00.000Z",
      lastSuccessAt: "2026-07-20T00:00:00.000Z",
      lastFailureAt: null,
      failureCount: 0,
      refreshStatus: "current",
      sourceChanged: false,
      manualReviewRequired: false,
      previousSource: snap({
        name: "Fixture Serum Current",
        officialUrl: "https://brand.example/serum",
        priceAmount: 28000,
        currency: "KRW",
        inStock: true,
        ingredientsFingerprint: "inci:abc",
        imageUrl: "https://cdn.example/serum.jpg",
      }),
      currentSource: snap({
        name: "Fixture Serum Current",
        officialUrl: "https://brand.example/serum",
        priceAmount: 28000,
        currency: "KRW",
        inStock: true,
        ingredientsFingerprint: "inci:abc",
        imageUrl: "https://cdn.example/serum.jpg",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "prod-due-002",
      entityKind: "product",
      displayName: "Fixture Toner Due",
      collectedAt: "2026-06-01T00:00:00.000Z",
      verifiedAt: "2026-06-01T00:00:00.000Z",
      refreshDueAt: "2026-07-01T00:00:00.000Z",
      lastSuccessAt: "2026-06-01T00:00:00.000Z",
      lastFailureAt: null,
      failureCount: 0,
      refreshStatus: "refresh_due",
      sourceChanged: false,
      manualReviewRequired: false,
      previousSource: snap({
        name: "Fixture Toner Due",
        officialUrl: "https://brand.example/toner",
        priceAmount: 18000,
        currency: "KRW",
        inStock: true,
        ingredientsFingerprint: "inci:toner1",
      }),
      currentSource: snap({
        name: "Fixture Toner Due",
        officialUrl: "https://brand.example/toner",
        priceAmount: 18000,
        currency: "KRW",
        inStock: true,
        ingredientsFingerprint: "inci:toner1",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "prod-changed-003",
      entityKind: "product",
      displayName: "Fixture Cream Reformulated",
      collectedAt: "2026-05-01T00:00:00.000Z",
      verifiedAt: "2026-05-01T00:00:00.000Z",
      refreshDueAt: "2026-07-20T00:00:00.000Z",
      lastSuccessAt: "2026-05-01T00:00:00.000Z",
      lastFailureAt: null,
      failureCount: 0,
      refreshStatus: "verification_required",
      sourceChanged: true,
      manualReviewRequired: true,
      previousSource: snap({
        name: "Fixture Cream",
        officialUrl: "https://brand.example/cream",
        priceAmount: 32000,
        currency: "KRW",
        inStock: true,
        ingredientsFingerprint: "inci:old",
        imageUrl: "https://cdn.example/cream-old.jpg",
      }),
      currentSource: snap({
        name: "Fixture Cream v2",
        officialUrl: "https://brand.example/cream",
        priceAmount: 34000,
        currency: "KRW",
        inStock: true,
        ingredientsFingerprint: "inci:new",
        imageUrl: "https://cdn.example/cream-new.jpg",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "prod-failed-004",
      entityKind: "product",
      displayName: "Fixture Mist Fetch Failed",
      collectedAt: "2026-07-10T00:00:00.000Z",
      verifiedAt: "2026-07-10T00:00:00.000Z",
      refreshDueAt: "2026-07-23T00:00:00.000Z",
      lastSuccessAt: "2026-07-01T00:00:00.000Z",
      lastFailureAt: "2026-07-23T08:00:00.000Z",
      failureCount: 2,
      refreshStatus: "refresh_failed",
      sourceChanged: false,
      manualReviewRequired: false,
      previousSource: snap({
        name: "Fixture Mist",
        officialUrl: "https://brand.example/mist",
        ingredientsFingerprint: "inci:mist",
      }),
      currentSource: snap({
        name: "Fixture Mist",
        officialUrl: "https://brand.example/mist",
        ingredientsFingerprint: "inci:mist",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "prod-hard-stale-005",
      entityKind: "product",
      displayName: "Fixture Ampoule Hard Stale",
      collectedAt: "2025-12-01T00:00:00.000Z",
      verifiedAt: "2025-12-01T00:00:00.000Z",
      refreshDueAt: "2026-01-01T00:00:00.000Z",
      lastSuccessAt: "2025-12-01T00:00:00.000Z",
      lastFailureAt: null,
      failureCount: 0,
      refreshStatus: "stale_but_usable",
      sourceChanged: false,
      manualReviewRequired: false,
      previousSource: snap({
        name: "Fixture Ampoule",
        officialUrl: "https://brand.example/ampoule",
        ingredientsFingerprint: "inci:amp",
      }),
      currentSource: snap({
        name: "Fixture Ampoule",
        officialUrl: "https://brand.example/ampoule",
        ingredientsFingerprint: "inci:amp",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "clinic-current-001",
      entityKind: "clinic",
      displayName: "Fixture Seoul Derm Current",
      collectedAt: "2026-06-01T00:00:00.000Z",
      verifiedAt: "2026-06-01T00:00:00.000Z",
      refreshDueAt: "2026-09-01T00:00:00.000Z",
      lastSuccessAt: "2026-06-01T00:00:00.000Z",
      lastFailureAt: null,
      failureCount: 0,
      refreshStatus: "current",
      sourceChanged: false,
      manualReviewRequired: false,
      previousSource: snap({
        name: "Fixture Seoul Derm Current",
        officialUrl: "https://hira.example/clinic/1",
        operatingStatus: "active",
        specialtyCount: 2,
        evidenceFingerprint: "ev:clinic1",
      }),
      currentSource: snap({
        name: "Fixture Seoul Derm Current",
        officialUrl: "https://hira.example/clinic/1",
        operatingStatus: "active",
        specialtyCount: 2,
        evidenceFingerprint: "ev:clinic1",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "clinic-due-002",
      entityKind: "clinic",
      displayName: "Fixture Gangnam Derm Due",
      collectedAt: "2026-01-01T00:00:00.000Z",
      verifiedAt: "2026-01-01T00:00:00.000Z",
      refreshDueAt: "2026-07-01T00:00:00.000Z",
      lastSuccessAt: "2026-01-01T00:00:00.000Z",
      lastFailureAt: null,
      failureCount: 0,
      refreshStatus: "refresh_due",
      sourceChanged: false,
      manualReviewRequired: false,
      previousSource: snap({
        name: "Fixture Gangnam Derm Due",
        officialUrl: "https://hira.example/clinic/2",
        operatingStatus: "active",
        specialtyCount: 1,
        evidenceFingerprint: "ev:clinic2",
      }),
      currentSource: snap({
        name: "Fixture Gangnam Derm Due",
        officialUrl: "https://hira.example/clinic/2",
        operatingStatus: "active",
        specialtyCount: 1,
        evidenceFingerprint: "ev:clinic2",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "clinic-changed-003",
      entityKind: "clinic",
      displayName: "Fixture Closed Derm",
      collectedAt: "2026-02-01T00:00:00.000Z",
      verifiedAt: "2026-02-01T00:00:00.000Z",
      refreshDueAt: "2026-07-20T00:00:00.000Z",
      lastSuccessAt: "2026-02-01T00:00:00.000Z",
      lastFailureAt: null,
      failureCount: 0,
      refreshStatus: "verification_required",
      sourceChanged: true,
      manualReviewRequired: true,
      previousSource: snap({
        name: "Fixture Closed Derm",
        officialUrl: "https://hira.example/clinic/3",
        operatingStatus: "active",
        specialtyCount: 3,
        evidenceFingerprint: "ev:clinic3-old",
      }),
      currentSource: snap({
        name: "Fixture Closed Derm",
        officialUrl: "https://hira.example/clinic/3",
        operatingStatus: "closed",
        specialtyCount: 3,
        evidenceFingerprint: "ev:clinic3-new",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "clinic-unavailable-004",
      entityKind: "clinic",
      displayName: "Fixture Source Unavailable",
      collectedAt: "2026-07-01T00:00:00.000Z",
      verifiedAt: "2026-07-01T00:00:00.000Z",
      refreshDueAt: "2026-07-22T00:00:00.000Z",
      lastSuccessAt: "2026-06-01T00:00:00.000Z",
      lastFailureAt: "2026-07-22T10:00:00.000Z",
      failureCount: 4,
      refreshStatus: "source_unavailable",
      sourceChanged: false,
      manualReviewRequired: true,
      previousSource: snap({
        name: "Fixture Source Unavailable",
        officialUrl: "https://hira.example/clinic/4",
        operatingStatus: "active",
        specialtyCount: 1,
        evidenceFingerprint: "ev:clinic4",
      }),
      currentSource: null,
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
    {
      entityId: "prod-exhausted-006",
      entityKind: "product",
      displayName: "Fixture Retry Exhausted",
      collectedAt: "2026-07-01T00:00:00.000Z",
      verifiedAt: "2026-07-01T00:00:00.000Z",
      refreshDueAt: "2026-07-24T00:00:00.000Z",
      lastSuccessAt: null,
      lastFailureAt: "2026-07-24T06:00:00.000Z",
      failureCount: 5,
      refreshStatus: "refresh_failed",
      sourceChanged: false,
      manualReviewRequired: true,
      previousSource: snap({
        name: "Fixture Retry Exhausted",
        officialUrl: "https://brand.example/gone",
      }),
      currentSource: snap({
        name: "Fixture Retry Exhausted",
        officialUrl: "https://brand.example/gone",
      }),
      isFixture: true,
      isDryRunRecord: true,
      allowPublicSurface: false,
      discontinued: false,
    },
  ];
}
