/**
 * KR bulk catalog seed templates — official-domain product line skeletons.
 * Full INCI is often incomplete → pipeline routes many rows to needs_review.
 * Image URLs are official remote references only (no unauthorized Storage copy).
 */

export type SeedProductTemplate = {
  nameKo: string;
  nameEn: string;
  category: string;
  volumeMl?: number;
  keyIngredients: string[];
  concerns: string[];
  usageArea: string;
  cautionHints: string[];
  /** Relative PDP path under brand official root */
  pathSlug: string;
  /** When false, mark incomplete ingredients */
  hasFullInciHint?: boolean;
  retailerHint?: "oliveyoung" | "official" | "none";
};

/** Shared skincare line templates rotated across brands */
export const LINE_TEMPLATES: SeedProductTemplate[] = [
  {
    nameKo: "센텔라 수딩 토너",
    nameEn: "Centella Soothing Toner",
    category: "toner",
    volumeMl: 200,
    keyIngredients: ["Centella Asiatica", "Panthenol", "Allantoin"],
    concerns: ["redness", "sensitivity"],
    usageArea: "face",
    cautionHints: ["패치 테스트 권장"],
    pathSlug: "centella-soothing-toner",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "히알루론산 수분 세럼",
    nameEn: "Hyaluronic Moisture Serum",
    category: "serum",
    volumeMl: 50,
    keyIngredients: ["Sodium Hyaluronate", "Panthenol", "Glycerin"],
    concerns: ["dryness"],
    usageArea: "face",
    cautionHints: ["세안 직후 사용"],
    pathSlug: "hyaluronic-moisture-serum",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "나이아신아마이드 세럼",
    nameEn: "Niacinamide Serum",
    category: "serum",
    volumeMl: 30,
    keyIngredients: ["Niacinamide", "Zinc PCA", "Allantoin"],
    concerns: ["acne", "pores", "pigmentation"],
    usageArea: "face",
    cautionHints: ["낮 자외선 차단 병행"],
    pathSlug: "niacinamide-serum",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "레티놀 크림",
    nameEn: "Retinol Cream",
    category: "cream",
    volumeMl: 20,
    keyIngredients: ["Retinol", "Adenosine", "Panthenol"],
    concerns: ["antiaging"],
    usageArea: "face",
    cautionHints: ["저녁 소량 시작", "주간 SPF 필수"],
    pathSlug: "retinol-cream",
    hasFullInciHint: true,
    retailerHint: "official",
  },
  {
    nameKo: "세라마이드 배리어 크림",
    nameEn: "Ceramide Barrier Cream",
    category: "cream",
    volumeMl: 80,
    keyIngredients: ["Ceramide", "Cholesterol", "Panthenol"],
    concerns: ["dryness", "sensitivity"],
    usageArea: "face",
    cautionHints: ["자극 시 중단"],
    pathSlug: "ceramide-barrier-cream",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "AHA BHA 토너",
    nameEn: "AHA BHA Clarifying Toner",
    category: "toner",
    volumeMl: 150,
    keyIngredients: ["Salicylic Acid", "Glycolic Acid", "Panthenol"],
    concerns: ["pores", "acne"],
    usageArea: "face",
    cautionHints: ["주간 SPF", "중복 산 사용 주의"],
    pathSlug: "aha-bha-clarifying-toner",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "비타민C 브라이트닝 세럼",
    nameEn: "Vitamin C Brightening Serum",
    category: "serum",
    volumeMl: 20,
    keyIngredients: ["Ascorbic Acid", "Niacinamide", "Tocopherol"],
    concerns: ["pigmentation", "uv"],
    usageArea: "face",
    cautionHints: ["민감 시 고함량 주의", "SPF 병행"],
    pathSlug: "vitamin-c-brightening-serum",
    hasFullInciHint: false,
    retailerHint: "official",
  },
  {
    nameKo: "선크림 SPF50+",
    nameEn: "Mineral Soft Sun Cream SPF50+",
    category: "sunscreen",
    volumeMl: 50,
    keyIngredients: ["Zinc Oxide", "Titanium Dioxide", "Panthenol"],
    concerns: ["uv"],
    usageArea: "face",
    cautionHints: ["충분량·재도포"],
    pathSlug: "mineral-soft-sun-cream",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "클렌징 젤",
    nameEn: "Gentle Cleansing Gel",
    category: "cleanser",
    volumeMl: 150,
    keyIngredients: ["Glycerin", "Panthenol", "Centella Asiatica"],
    concerns: ["sensitivity", "redness"],
    usageArea: "face",
    cautionHints: ["눈 주위 주의"],
    pathSlug: "gentle-cleansing-gel",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "스네일 에센스",
    nameEn: "Snail Mucin Essence",
    category: "essence",
    volumeMl: 100,
    keyIngredients: ["Snail Secretion Filtrate", "Sodium Hyaluronate"],
    concerns: ["dryness", "redness"],
    usageArea: "face",
    cautionHints: ["알레르기 체크"],
    pathSlug: "snail-mucin-essence",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "펩타이드 아이크림",
    nameEn: "Peptide Eye Cream",
    category: "eye_cream",
    volumeMl: 30,
    keyIngredients: ["Peptide", "Adenosine", "Niacinamide"],
    concerns: ["antiaging"],
    usageArea: "eye",
    cautionHints: ["눈 점막 접촉 금지"],
    pathSlug: "peptide-eye-cream",
    hasFullInciHint: false,
    retailerHint: "official",
  },
  {
    nameKo: "티트리 스팟",
    nameEn: "Tea Tree Spot Treatment",
    category: "treatment",
    volumeMl: 15,
    keyIngredients: ["Tea Tree", "Centella Asiatica", "Salicylic Acid"],
    concerns: ["acne"],
    usageArea: "face",
    cautionHints: ["국소만 사용"],
    pathSlug: "tea-tree-spot-treatment",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "아르부틴 크림",
    nameEn: "Arbutin Tone Cream",
    category: "cream",
    volumeMl: 50,
    keyIngredients: ["Arbutin", "Niacinamide", "Panthenol"],
    concerns: ["pigmentation"],
    usageArea: "face",
    cautionHints: ["주간 SPF"],
    pathSlug: "arbutin-tone-cream",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "판테놀 미스트",
    nameEn: "Panthenol Comfort Mist",
    category: "mist",
    volumeMl: 100,
    keyIngredients: ["Panthenol", "Allantoin", "Centella Asiatica"],
    concerns: ["redness", "sensitivity", "dryness"],
    usageArea: "face",
    cautionHints: ["눈 스프레이 주의"],
    pathSlug: "panthenol-comfort-mist",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "그린티 클렌징 폼",
    nameEn: "Green Tea Foam Cleanser",
    category: "cleanser",
    volumeMl: 150,
    keyIngredients: ["Green Tea", "Glycerin", "Betaine"],
    concerns: ["sensitivity"],
    usageArea: "face",
    cautionHints: ["과도한 세안 주의"],
    pathSlug: "green-tea-foam-cleanser",
    hasFullInciHint: false,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "바쿠치올 세럼",
    nameEn: "Bakuchiol Serum",
    category: "serum",
    volumeMl: 30,
    keyIngredients: ["Bakuchiol", "Squalane", "Ceramide"],
    concerns: ["antiaging", "sensitivity"],
    usageArea: "face",
    cautionHints: ["저녁 사용 권장"],
    pathSlug: "bakuchiol-serum",
    hasFullInciHint: true,
    retailerHint: "official",
  },
  {
    nameKo: "프로폴리스 앰플",
    nameEn: "Propolis Ampoule",
    category: "ampoule",
    volumeMl: 30,
    keyIngredients: ["Propolis", "Honey Extract", "Panthenol"],
    concerns: ["dryness", "redness"],
    usageArea: "face",
    cautionHints: ["벌 관련 알레르기 주의"],
    pathSlug: "propolis-ampoule",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "병풀 크림",
    nameEn: "Cica Recovery Cream",
    category: "cream",
    volumeMl: 60,
    keyIngredients: ["Centella Asiatica", "Madecassoside", "Panthenol"],
    concerns: ["redness", "sensitivity"],
    usageArea: "face",
    cautionHints: ["패치 테스트"],
    pathSlug: "cica-recovery-cream",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "저자극 선스틱",
    nameEn: "Mild Sun Stick SPF50+",
    category: "sunscreen",
    volumeMl: 19,
    keyIngredients: ["Zinc Oxide", "Niacinamide", "Panthenol"],
    concerns: ["uv", "pigmentation"],
    usageArea: "face",
    cautionHints: ["재도포"],
    pathSlug: "mild-sun-stick",
    hasFullInciHint: false,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "어성초 토너",
    nameEn: "Heartleaf Toner",
    category: "toner",
    volumeMl: 250,
    keyIngredients: ["Heartleaf", "Panthenol", "Glycerin"],
    concerns: ["acne", "redness", "sensitivity"],
    usageArea: "face",
    cautionHints: ["냉장 보관 가능"],
    pathSlug: "heartleaf-toner",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "모공 클레이 마스크",
    nameEn: "Pore Clay Mask",
    category: "mask",
    volumeMl: 100,
    keyIngredients: ["Kaolin", "Salicylic Acid", "Centella Asiatica"],
    concerns: ["pores"],
    usageArea: "face",
    cautionHints: ["주 1~2회", "건조 전 제거"],
    pathSlug: "pore-clay-mask",
    hasFullInciHint: false,
    retailerHint: "oliveyoung",
  },
  {
    nameKo: "수분 젤 크림",
    nameEn: "Watery Gel Cream",
    category: "cream",
    volumeMl: 70,
    keyIngredients: ["Sodium Hyaluronate", "Betaine", "Panthenol"],
    concerns: ["dryness"],
    usageArea: "face",
    cautionHints: ["지성도 가볍게 사용"],
    pathSlug: "watery-gel-cream",
    hasFullInciHint: true,
    retailerHint: "oliveyoung",
  },
];
