/**
 * Gate candidate fixtures covering unsafe + eligible paths.
 * Includes a non-fixture dry-run official row for structural publishable proof.
 */

import type { AdminGateCandidateInput } from "./types";

/** Fixed ISO for deterministic selftests. */
export const FIXTURE_NOW_ISO = "2026-07-24T05:00:00.000Z";

export function getFixtureGateCandidates(): AdminGateCandidateInput[] {
  return [
    // Fixture enriched derm — must never publish / never public
    {
      recordId: "gate-fixture-derm-001",
      institutionId: "FIXTURE-YKIHO-SEOUL-DERM-001",
      name: "[FIXTURE] 서울 피부과 예시의원",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "enriched",
      enrichmentEvidenceStrength: "strong",
      conflictingSource: false,
      dermatologyDeptOfficial: true,
      dermatologySpecialistCount: 2,
      symptomEvidenceReviewerStatus: "approved",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "none",
      adminApproved: true,
      adminApprovedAt: FIXTURE_NOW_ISO,
      adminApproverLabel: "fixture-admin",
      isFixture: true,
      hasRequiredOfficialEvidence: true,
    },
    // Failed enrichment
    {
      recordId: "gate-failed-retryable-009",
      institutionId: "FIXTURE-YKIHO-FAIL-RETRY-009",
      name: "[FIXTURE] 재시도 실패 예시",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "failed_retryable",
      enrichmentEvidenceStrength: "none",
      conflictingSource: false,
      dermatologyDeptOfficial: null,
      dermatologySpecialistCount: null,
      symptomEvidenceReviewerStatus: "absent",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "none",
      adminApproved: false,
      adminApprovedAt: null,
      adminApproverLabel: null,
      isFixture: true,
      hasRequiredOfficialEvidence: false,
    },
    // Stale ingestion
    {
      recordId: "gate-stale-010",
      institutionId: "FIXTURE-YKIHO-STALE-010",
      name: "[FIXTURE] 스테일 예시의원",
      ingestionStatus: "stale",
      enrichmentStatus: "enriched",
      enrichmentEvidenceStrength: "moderate",
      conflictingSource: false,
      dermatologyDeptOfficial: true,
      dermatologySpecialistCount: 1,
      symptomEvidenceReviewerStatus: "stale",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "none",
      adminApproved: true,
      adminApprovedAt: FIXTURE_NOW_ISO,
      adminApproverLabel: "fixture-admin",
      isFixture: true,
      hasRequiredOfficialEvidence: true,
    },
    // Conflicting source
    {
      recordId: "gate-conflict-007",
      institutionId: "FIXTURE-YKIHO-CONFLICT-007",
      name: "[FIXTURE] 출처충돌 예시의원",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "needs_manual_review",
      enrichmentEvidenceStrength: "weak",
      conflictingSource: true,
      dermatologyDeptOfficial: false,
      dermatologySpecialistCount: 2,
      symptomEvidenceReviewerStatus: "pending_review",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "none",
      adminApproved: false,
      adminApprovedAt: null,
      adminApproverLabel: null,
      isFixture: true,
      hasRequiredOfficialEvidence: true,
    },
    // Insufficient evidence (no official derm)
    {
      recordId: "gate-insufficient-005",
      institutionId: "FIXTURE-YKIHO-SEOUL-FAKE-DERM-NAME-005",
      name: "[FIXTURE] 마케팅용 피부과 간판 내과",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "needs_manual_review",
      enrichmentEvidenceStrength: "none",
      conflictingSource: false,
      dermatologyDeptOfficial: false,
      dermatologySpecialistCount: 1,
      symptomEvidenceReviewerStatus: "needs_more_evidence",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "none",
      adminApproved: false,
      adminApprovedAt: null,
      adminApproverLabel: null,
      isFixture: true,
      hasRequiredOfficialEvidence: false,
    },
    // Paid relationship — fixture, admin review path only for paid lane
    {
      recordId: "gate-paid-affiliate-011",
      institutionId: "FIXTURE-YKIHO-PAID-011",
      name: "[FIXTURE] 제휴 피부과 예시",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "enriched",
      enrichmentEvidenceStrength: "strong",
      conflictingSource: false,
      dermatologyDeptOfficial: true,
      dermatologySpecialistCount: 3,
      symptomEvidenceReviewerStatus: "approved",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "affiliate",
      adminApproved: false,
      adminApprovedAt: null,
      adminApproverLabel: null,
      isFixture: true,
      hasRequiredOfficialEvidence: true,
    },
    // Dry-run official (non-fixture): missing admin approval → review eligible only
    {
      recordId: "gate-dry-run-official-pending",
      institutionId: "DRYRUN-YKIHO-SEOUL-DERM-100",
      name: "[DRY-RUN] 서울 공식 피부과 후보(미승인)",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "enriched",
      enrichmentEvidenceStrength: "strong",
      conflictingSource: false,
      dermatologyDeptOfficial: true,
      dermatologySpecialistCount: 2,
      symptomEvidenceReviewerStatus: "absent",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "none",
      adminApproved: false,
      adminApprovedAt: null,
      adminApproverLabel: null,
      isFixture: false,
      hasRequiredOfficialEvidence: true,
    },
    // Dry-run official + admin approved → structurally publishable (still not public)
    {
      recordId: "gate-dry-run-official-approved",
      institutionId: "DRYRUN-YKIHO-SEOUL-DERM-101",
      name: "[DRY-RUN] 서울 공식 피부과 후보(승인)",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "enriched",
      enrichmentEvidenceStrength: "strong",
      conflictingSource: false,
      dermatologyDeptOfficial: true,
      dermatologySpecialistCount: 4,
      symptomEvidenceReviewerStatus: "absent",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "none",
      adminApproved: true,
      adminApprovedAt: FIXTURE_NOW_ISO,
      adminApproverLabel: "dry-run-admin",
      isFixture: false,
      hasRequiredOfficialEvidence: true,
    },
    // Dry-run official with paid commercial — structural ok if approved; Organic independent
    {
      recordId: "gate-dry-run-official-paid",
      institutionId: "DRYRUN-YKIHO-SEOUL-DERM-102",
      name: "[DRY-RUN] 서울 공식 피부과(유료관계)",
      ingestionStatus: "candidate_ready",
      enrichmentStatus: "enriched",
      enrichmentEvidenceStrength: "moderate",
      conflictingSource: false,
      dermatologyDeptOfficial: true,
      dermatologySpecialistCount: 1,
      symptomEvidenceReviewerStatus: "approved",
      symptomEvidencePublishEligible: false,
      commercialRelationship: "booking_fee",
      adminApproved: true,
      adminApprovedAt: FIXTURE_NOW_ISO,
      adminApproverLabel: "dry-run-admin",
      isFixture: false,
      hasRequiredOfficialEvidence: true,
    },
  ];
}
