/**
 * Fixture offers / placements for P3-T04 revenue readiness (non-public).
 * Uses example hosts only — never invents live commercial URLs or rates.
 */

import type {
  AffiliateOfferIngestInput,
  ClickConversionEventInput,
  SponsoredPlacementContractInput,
} from "./types";

export function createAffiliateOfferFixtures(): AffiliateOfferIngestInput[] {
  return [
    {
      offerId: "aff-ok-kr-001",
      productId: "prod-serum-001",
      partnerId: "partner-fixture-a",
      campaignId: "camp-fixture-serum",
      commission: {
        commissionType: "cps",
        commissionRatePercent: null,
        commissionRateKnown: false,
        commissionAmountKnown: false,
        commissionAmount: null,
        currency: null,
      },
      countryLinks: [
        {
          countryCode: "KR",
          languageCode: "ko",
          currency: "KRW",
          purchaseUrl: "https://shop.example.kr/serum",
          shipsToCountry: true,
          inStock: true,
          verifiedAt: "2026-07-20T00:00:00.000Z",
          isFixtureUrl: true,
        },
        {
          countryCode: "US",
          languageCode: "en",
          currency: "USD",
          purchaseUrl: "https://shop.example.com/us/serum",
          shipsToCountry: true,
          inStock: null,
          verifiedAt: "2026-07-20T00:00:00.000Z",
          isFixtureUrl: true,
        },
      ],
      disclosureLabelKo: null,
      disclosureLabelEn: null,
      startsAt: "2026-07-01T00:00:00.000Z",
      expiresAt: "2026-12-31T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
    },
    {
      offerId: "aff-invented-rate-002",
      productId: "prod-toner-002",
      partnerId: "partner-fixture-b",
      campaignId: "camp-bad-rate",
      commission: {
        commissionType: "cps",
        commissionRatePercent: null,
        commissionRateKnown: true,
        commissionAmountKnown: false,
        commissionAmount: null,
        currency: null,
      },
      countryLinks: [
        {
          countryCode: "KR",
          languageCode: "ko",
          currency: "KRW",
          purchaseUrl: "https://shop.example.kr/toner",
          shipsToCountry: true,
          inStock: true,
          verifiedAt: "2026-07-20T00:00:00.000Z",
          isFixtureUrl: true,
        },
      ],
      disclosureLabelKo: null,
      disclosureLabelEn: null,
      startsAt: "2026-07-01T00:00:00.000Z",
      expiresAt: "2026-12-31T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
      inventedCommissionRate: true,
    },
    {
      offerId: "aff-expired-003",
      productId: "prod-cream-003",
      partnerId: "partner-fixture-c",
      campaignId: "camp-expired",
      commission: {
        commissionType: "cpa",
        commissionRatePercent: null,
        commissionRateKnown: false,
        commissionAmountKnown: false,
        commissionAmount: null,
        currency: null,
      },
      countryLinks: [
        {
          countryCode: "KR",
          languageCode: "ko",
          currency: "KRW",
          purchaseUrl: "https://shop.example.kr/cream",
          shipsToCountry: true,
          inStock: false,
          verifiedAt: "2026-01-01T00:00:00.000Z",
          isFixtureUrl: true,
        },
      ],
      disclosureLabelKo: null,
      disclosureLabelEn: null,
      startsAt: "2025-01-01T00:00:00.000Z",
      expiresAt: "2026-01-01T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
    },
    {
      offerId: "aff-no-country-004",
      productId: "prod-mask-004",
      partnerId: "partner-fixture-d",
      campaignId: "camp-no-country",
      commission: {
        commissionType: "unknown",
        commissionRatePercent: null,
        commissionRateKnown: false,
        commissionAmountKnown: false,
        commissionAmount: null,
        currency: null,
      },
      countryLinks: [],
      disclosureLabelKo: null,
      disclosureLabelEn: null,
      startsAt: "2026-07-01T00:00:00.000Z",
      expiresAt: "2026-12-31T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
    },
    {
      offerId: "aff-organic-lookalike-005",
      productId: "prod-ampoule-005",
      partnerId: "partner-fixture-e",
      campaignId: "camp-lookalike",
      commission: {
        commissionType: "cps",
        commissionRatePercent: null,
        commissionRateKnown: false,
        commissionAmountKnown: false,
        commissionAmount: null,
        currency: null,
      },
      countryLinks: [
        {
          countryCode: "KR",
          languageCode: "ko",
          currency: "KRW",
          purchaseUrl: "https://shop.example.kr/ampoule",
          shipsToCountry: true,
          inStock: true,
          verifiedAt: "2026-07-20T00:00:00.000Z",
          isFixtureUrl: true,
        },
      ],
      disclosureLabelKo: "유기적 추천 1위 제품입니다",
      disclosureLabelEn: "Best organic recommendation for you",
      startsAt: "2026-07-01T00:00:00.000Z",
      expiresAt: "2026-12-31T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
    },
  ];
}

export function createSponsoredPlacementFixtures(): SponsoredPlacementContractInput[] {
  return [
    {
      placementId: "sp-rail-001",
      entityType: "product",
      entityId: "prod-serum-001",
      partnerId: "sponsor-fixture-a",
      campaignId: "sp-camp-rail",
      sponsoredPlacementRank: 1,
      zone: "sponsored_rail",
      disclosureLabelKo: null,
      disclosureLabelEn: null,
      startsAt: "2026-07-01T00:00:00.000Z",
      expiresAt: "2026-12-31T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
    },
    {
      placementId: "sp-organic-forbidden-002",
      entityType: "product",
      entityId: "prod-toner-002",
      partnerId: "sponsor-fixture-b",
      campaignId: "sp-camp-organic",
      sponsoredPlacementRank: 1,
      zone: "sponsored_rail",
      disclosureLabelKo: null,
      disclosureLabelEn: null,
      startsAt: "2026-07-01T00:00:00.000Z",
      expiresAt: "2026-12-31T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
      attemptedOrganicZone: true,
    },
    {
      placementId: "sp-clinic-aside-003",
      entityType: "clinic",
      entityId: "clinic-fixture-001",
      partnerId: "sponsor-clinic-a",
      campaignId: "sp-camp-clinic",
      sponsoredPlacementRank: 2,
      zone: "clinic_partner_aside",
      disclosureLabelKo: null,
      disclosureLabelEn: null,
      startsAt: "2026-07-01T00:00:00.000Z",
      expiresAt: "2026-12-31T00:00:00.000Z",
      evidenceVerified: true,
      isFixture: true,
    },
  ];
}

export function createClickConversionEventFixtures(): ClickConversionEventInput[] {
  return [
    {
      eventId: "evt-click-001",
      kind: "click",
      lane: "affiliate",
      entityType: "product",
      entityId: "prod-serum-001",
      offerOrPlacementId: "aff-ok-kr-001",
      countryCode: "KR",
    },
    {
      eventId: "evt-conv-002",
      kind: "conversion",
      lane: "affiliate",
      entityType: "product",
      entityId: "prod-serum-001",
      offerOrPlacementId: "aff-ok-kr-001",
      countryCode: "KR",
      // Explicit null — do not invent revenue.
      revenueAmount: null,
      currency: null,
    },
    {
      eventId: "evt-health-forbidden-003",
      kind: "click",
      lane: "sponsored",
      entityType: "product",
      entityId: "prod-serum-001",
      offerOrPlacementId: "sp-rail-001",
      countryCode: "KR",
      targetingProfile: {
        symptoms: ["acne"],
        skinConcerns: ["redness"],
      },
    },
  ];
}
