/**
 * Fixture rows for T07-04 — cover all four claim categories + policy blocks.
 * Non-public. Never claim as live publishable symptom expertise.
 */

import type { SymptomEvidenceManifestInput } from "./types";

const VERIFIED = "2026-07-20T00:00:00.000Z";
const STALE_FUTURE = "2026-12-31T00:00:00.000Z";
const STALE_PAST = "2026-01-01T00:00:00.000Z";

export function getFixtureSymptomEvidenceInputs(): SymptomEvidenceManifestInput[] {
  return [
    {
      evidenceId: "fx-acne-official-approved",
      sourceId: "official-hospital-page",
      claimCategory: "acne",
      evidenceUrl: "https://hospital.example.kr/care/acne",
      pageTitle: "여드름 진료 안내 (공식)",
      excerptSummary: "여드름은 피부과 진료가 필요할 수 있으며 자가진단이 아닙니다.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "approved",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: "예시피부과의원",
      isFixture: false,
      accessMode: "manifest_manual",
    },
    {
      evidenceId: "fx-rosacea-official-pending",
      sourceId: "official-hospital-page",
      claimCategory: "rosacea_redness",
      evidenceUrl: "https://hospital.example.kr/care/rosacea",
      pageTitle: "주사·홍조 진료 안내",
      excerptSummary: "지속 홍조·혈관 확장은 전문의 상담을 권고합니다.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "pending_review",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: "예시피부과의원",
      isFixture: false,
      accessMode: "manifest_manual",
    },
    {
      evidenceId: "fx-atopic-approved-public",
      sourceId: "approved-public-evidence",
      claimCategory: "atopic_dermatitis",
      evidenceUrl: "https://public-health.example.kr/atopic",
      pageTitle: "아토피피부염 공개 안내",
      excerptSummary: "아토피피부염은 만성 염증성 피부질환으로 전문가 관리가 필요합니다.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "approved",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: null,
      isFixture: false,
      accessMode: "public_https_paste",
    },
    {
      evidenceId: "fx-pigmentation-affiliate",
      sourceId: "official-hospital-page",
      claimCategory: "pigmentation",
      evidenceUrl: "https://partner-clinic.example.kr/pigment",
      pageTitle: "색소 클리닉 (제휴)",
      excerptSummary: "색소 치료 안내 — 제휴 예약 수수료 있음.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "approved",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "affiliate",
      commercialDisclosureKo: "예약 수수료·제휴 관계가 있습니다.",
      clinicOrInstitutionLabel: "제휴클리닉",
      isFixture: false,
      accessMode: "manifest_manual",
    },
    {
      evidenceId: "fx-acne-sponsored",
      sourceId: "official-hospital-page",
      claimCategory: "acne",
      evidenceUrl: "https://sponsored.example.kr/acne",
      pageTitle: "스폰서 여드름 특집",
      excerptSummary: "광고비 지원 콘텐츠.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "approved",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "sponsored",
      commercialDisclosureKo: "스폰서 콘텐츠입니다.",
      clinicOrInstitutionLabel: "스폰서클리닉",
      isFixture: false,
      accessMode: "manifest_manual",
    },
    {
      evidenceId: "fx-rosacea-stale",
      sourceId: "official-hospital-page",
      claimCategory: "rosacea_redness",
      evidenceUrl: "https://hospital.example.kr/care/rosacea-old",
      pageTitle: "구버전 홍조 안내",
      excerptSummary: "오래된 안내 페이지.",
      verifiedAt: "2025-01-01T00:00:00.000Z",
      staleAt: STALE_PAST,
      reviewerStatus: "stale",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: "예시피부과의원",
      isFixture: false,
      accessMode: "manifest_manual",
    },
    {
      evidenceId: "fx-atopic-rejected",
      sourceId: "official-hospital-page",
      claimCategory: "atopic_dermatitis",
      evidenceUrl: "https://hospital.example.kr/care/atopic-weak",
      pageTitle: "근거 부족 페이지",
      excerptSummary: "발췌가 증상 전문 주장을 뒷받침하지 않음.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "rejected",
      rejectionReasonCode: "medical_claim_unverified",
      rejectionReasonKo: "발췌가 증상 전문 주장을 뒷받침하지 않습니다.",
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: "예시피부과의원",
      isFixture: false,
      accessMode: "manifest_manual",
    },
    {
      evidenceId: "fx-pigmentation-captcha-block",
      sourceId: "captcha-blocked",
      claimCategory: "pigmentation",
      evidenceUrl: "https://walled.example.kr/pigment",
      pageTitle: "CAPTCHA 벽",
      excerptSummary: "자동 수집 시도 금지 대상.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "pending_review",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: null,
      isFixture: false,
      accessMode: "blocked_captcha",
    },
    {
      evidenceId: "fx-acne-login-block",
      sourceId: "auth-wall-blocked",
      claimCategory: "acne",
      evidenceUrl: "https://members.example.kr/acne",
      pageTitle: "회원 전용",
      excerptSummary: "로그인 자동화 금지.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "pending_review",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: null,
      isFixture: false,
      accessMode: "blocked_auth_required",
    },
    {
      evidenceId: "fx-marketplace-blocked",
      sourceId: "marketplace-blog-blocked",
      claimCategory: "acne",
      evidenceUrl: "https://blog.example.kr/acne-tips",
      pageTitle: "블로그 팁",
      excerptSummary: "마켓/블로그 단독 근거 불가.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "pending_review",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: null,
      isFixture: false,
      accessMode: "manifest_manual",
    },
    {
      evidenceId: "fx-offline-fixture-only",
      sourceId: "fixture-offline",
      claimCategory: "pigmentation",
      evidenceUrl: "fixture://offline/pigmentation",
      pageTitle: "오프라인 fixture",
      excerptSummary: "테스트 전용 · 게시 금지.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "approved",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: "fixture",
      isFixture: true,
      accessMode: "offline_fixture",
    },
    {
      evidenceId: "fx-needs-more-evidence",
      sourceId: "approved-public-evidence",
      claimCategory: "atopic_dermatitis",
      evidenceUrl: "https://public-health.example.kr/atopic-partial",
      pageTitle: "부분 근거",
      excerptSummary: "추가 공식 페이지 확인 필요.",
      verifiedAt: VERIFIED,
      staleAt: STALE_FUTURE,
      reviewerStatus: "needs_more_evidence",
      rejectionReasonCode: null,
      rejectionReasonKo: null,
      commercialRelationship: "none",
      commercialDisclosureKo: null,
      clinicOrInstitutionLabel: null,
      isFixture: false,
      accessMode: "public_https_paste",
    },
  ];
}
